AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  back-end-practice

  Sample SAM Template for back-end-practice

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  # data base resource
  MyDynamoDBTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: items
      PrimaryKey:
        Name: id
        Type: String

  # API resource
  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      DefinitionBody:
              swagger: '2.0'
              info:
                title: My API
              paths: # paths that the api has
                /items:
                  post: # items POST protocol
                    x-amazon-apigateway-integration:
                      httpMethod: POST
                      type: aws_proxy
                      uri: # connect to lambda function resource
                        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostLambdaFunction.Arn}/invocations
                      responses: {}
                /items/{id}: # items path
                  get: # items GET protocol
                    x-amazon-apigateway-integration:
                      httpMethod: POST
                      type: aws_proxy
                      uri: # connect to lambda function resource
                        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetLambdaFunction.Arn}/invocations
                      responses: {}
                  put: #items PUT protocol
                    x-amazon-apigateway-integration:
                      httpMethod: POST
                      type: aws_proxy
                      uri: # connect to lambda function resource
                        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PutLambdaFunction.Arn}/invocations
                      responses: {}
                  
  # lambda function resource for GET protocol
  GetLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src
      Handler: get.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: get
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTable
  
  # permission that allows api to invoke GET protocol lambda function
  GetLambdaFunctionApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetLambdaFunction
      Principal: apigateway.amazonaws.com

  # lambda function resource for POST protocol
  PostLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src
      Handler: post.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTable

  # permission that allows api to invoke POST protocol lambda function
  PostLambdaFunctionApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PostLambdaFunction
      Principal: apigateway.amazonaws.com

  # lambda function resource for PUT protocol
  PutLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src
      Handler: put.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: put
            RestApiId: !Ref MyApi
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTable

  # permission that allows api to invoke PUT protocol lambda function
  PutLambdaFunctionApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PutLambdaFunction
      Principal: apigateway.amazonaws.com

  # CloudWatch Logs Managed Policy
  CloudWatchLogsPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Managed Policy for CloudWatch Logs Access'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 'arn:aws:logs:*:*:*' # This gives access to all logs, consider narrowing the scope

  # DynamoDB Policy
  DynamoDBPutItemPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: 'Managed Policy for DynamoDB PutItem'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource: '*'

  # IAM Role for Lambda with both Managed Policies attached
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'YourLambdaRoleName'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 
              - 'lambda.amazonaws.com'
          Action:
            - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref CloudWatchLogsPolicy
        - !Ref DynamoDBPutItemPolicy
