AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-hello-world

  Sample SAM Template for aws-hello-world

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  MyApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod
      DefinitionBody:
              swagger: '2.0'
              info:
                title: My API
              paths:
                /items:
                  get:
                    responses:
                      '200':
                        description: OK
                    x-amazon-apigateway-integration:
                      httpMethod: POST
                      type: aws_proxy
                      uri:
                        Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
                      responses: {}
  
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src
      Handler: get.lambda_handler  # Update this to match your actual handler
      Runtime: python3.9  # Update to your desired runtime

  MyLambdaFunctionApiInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MyLambdaFunction
      Principal: apigateway.amazonaws.com

